site_name: Google Maps API Documentation
site_url: https://localhost:8000/
nav:
  - Home: index.md
  - "Developer's Guide": developers-guide.md
  - "How-to Guide": how-to-guide.md
  - "Code Samples": code-samples.md
  - "Reference Guide": reference-guide.md
  - "Change History": change-history.md
  - "Design Thinking Process & Impact": design-thinking.md
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: dark grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - header.autohide
    - announce.dismiss
extra:
  announcement:
    type: info
    text: "Explore our comprehensive Google Maps API documentation."
 
  footer:
    copyright: "© 2024 Google Maps API Documentation. All rights reserved."
  extra_css:
    - assets/custom-tiles.css
plugins:
  - search
 
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
